### ISSUE TITLE
running setup.sh in Ubuntu 16 - ruby error

### ISSUE THREAD

**Issue by tombisho** [nparley/datashield#6]
I got the following error

ERROR:  Error installing r10k:
        cri requires Ruby version ~> 2.3.

I realised I didn't have ruby installed, so now I do:

user@puppet:~$ ruby -v
ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]

but the error remains, so in the end I had to do:

sudo gem install r10k

**Comment by StuartWheater** [comment]
Current 'ubuntu16' branch use the latest version of Ruby and n10k.
